return {
    Shop = { 
	  "Watering Can",
	  "Trading Ticket",
	  "Trowel",
	  "Recall Wrench",
	  "Basic Sprinkler",
	  "Advanced Sprinkler",
	  "Medium Toy",
	  "Medium Treat",
	  "Godly Sprinkler",
	  "Magnifying Glass",
	  "Master Sprinkler",
	  "Cleaning Spray",
	  "Cleansing Pet Shard",
	  "Favorite Tool",
	  "Harvest Tool",
	  "Grandmaster Sprinkler",
	  "Levelup Lollipop",
    },
}
