return {
    Shop = { 
    "Carrot",
    "Strawberry",
    "Blueberry",
    "Orange Tulip",
    "Tomato",
    "Corn",
    "Daffodil",
    "Watermelon",
    "Pumpkin",
    "Apple",
    "Bamboo",
    "Coconut",
    "Cactus",
    "Dragon Fruit",
    "Mango",
    "Grape",
    "Mushroom",
    "Pepper",
    "Cacao",
    "Beanstalk",
    "Ember Lily",
    "Sugar Apple",
    "Burning Bud",
    "Elder Strawberry",
    "Giant Pinecone",
    "Romanesco",
    "Crimson Thorn",
    "Great Pumpkin",
    },
    
    Battlepass = { 
    "Strawberry",
    "Blueberry",
    "Tomato",
    "Corn",
    "Apple",
    "Coconut",
    "Cactus",
    "Dragon Fruit",
    "Mango",
    "Grape",
    "Pepper",
    "Cacao",
    "Beanstalk",
    "Ember Lily",
    "Sugar Apple",
    "Burning Bud",
    "Elder Strawberry",
    "Giant Pinecone",
    "Romanesco",
    "Crimson Thorn",
    },
    
    Event = { 
    "Poison Apple",
    "Seer Vine",
    "Chicken Feed",
    "Ghoul Root",
    "Jack O Lantern",
    "Bloodred Mushroom"
    },

}
