return {
    Shop = { 
    "Carrot",
    "Strawberry",
    "Blueberry",
    "Orange Tulip",
    "Tomato",
    "Corn",
    "Daffodil",
    "Watermelon",
    "Pumpkin",
    "Apple",
    "Bamboo",
    "Coconut",
    "Cactus",
    "Dragon Fruit",
    "Mango",
    "Grape",
    "Mushroom",
    "Pepper",
    "Cacao",
    "Beanstalk",
    "Ember Lily",
    "Sugar Apple",
    "Burning Bud",
    "Elder Strawberry",
    "Giant Pinecone",
    "Romanesco",
    "Crimson Thorn",
    "Great Pumpkin",
    },
    
    Battlepass = { 
    "Strawberry",
    "Blueberry",
    "Tomato",
    "Corn",
    "Apple",
    "Coconut",
    "Cactus",
    "Dragon Fruit",
    "Mango",
    "Grape",
    "Pepper",
    "Cacao",
    "Beanstalk",
    "Ember Lily",
    "Sugar Apple",
    "Burning Bud",
    "Elder Strawberry",
    "Giant Pinecone",
    "Romanesco",
    "Crimson Thorn",
    },
    
    Evo = { 
    "Evo Mushroom III",
    "Evo Mushroom II",
    "Evo Mushroom I",

    "Evo Blueberry III",
    "Evo Blueberry II",
    "Evo Blueberry I",

    "Evo Beetroot III",
    "Evo Beetroot II",
    "Evo Beetroot I",

    "Evo Pumpkin III",
    "Evo Pumpkin II",
    "Evo Pumpkin I"
    },

}
